version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      path: package

build:
  os: ubuntu-22.04
  tools:
    python: 3.9