
site_name: ardilla
site_url: https://ardilla.rtfm.com/

nav:
  - Guide:
    - guide/getting_started.md
    - guide/models.md
    - guide/fields.md
    - guide/engine.md
    - guide/crud.md
  - API Reference:
    - api_ref/crud.md
    - api_ref/model.md
    - api_ref/engine.md
  - Licence: licence.md
  - Library Alternatives: ardilla_alternatives.md

extra_css:
  - css/custom.css

plugins:
  - mkdocstrings

