[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ardilla"
version = "0.5.1-beta"
authors = [
  { name="ChrisDewa", email="chrisdewa@duck.com" },
]
description = "Ardilla ORM. Easy to use, fast to implement, with sync and async flavors"
readme = "README.md"
requires-python = ">=3.9"

classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Development Status :: 4 - Beta",
]
dependencies = [
  "pydantic>=2.0",
]


[project.optional-dependencies]
async = ["aiosqlite>=0.19",]

examples = [
  "fastapi>=0.100",
  "uvicorn>=0.23",
]

dev = [
  "pytest>=7.4",
  "pytest-asyncio>=0.23",
  "black>=24",
]
docs = [
  "mkdocs>=1.5",
  "mkdocstrings[python]>=0.24",
  "pymdown-extensions>=10.14",
]

[project.urls]
"Homepage" = "https://github.com/chrisdewa/ardilla"
"Bug Tracker" = "https://github.com/chrisdewa/ardilla/issues"
